export enum VisitaStatus {
  AGENDADO = 'AGENDADO',
  NAO_COMPARECEU = 'NÃO COMPARECEU',
  SEM_INTERESSE = 'SEM INTERESSE',
  PENSANDO = 'PENSANDO',
  RETORNO = 'RETORNO',
  MATRICULADO = 'MATRICULADO'
}
